### PR TITLE
fix: success message without successful result

### LINKED ISSUE #1: Created tasks don't show up in my Makerlog account
I successfully logged in via makerlog-cli. Downloaded the latest release of alfred workflow. Appended makelog to all the available actions ("makerlog todo", etc.). When I submit a todo via alfredI get a success message, but nothing shows up in the account.

This might be vague, but do you have any idea why that might be happening? 
Thanks in advance.

### PR DESCRIPTION
**Pull request by natterstefan**
image

## What I have done

- resolves https://github.com/meSingh/alfred-makerlog/issues/1
  - other configuration files than the hardcoded one can be used (e.g. `/Users/natterstefan/.zshrc`)
  - command does not send success but error push notification when either
    - the configuration file does not exist
    - or the task could not be completed (this might need some improvements in the future)
- optimized Workflow and use only one "Run Script" for all three entry points
- optimized README (eg. max. 80 chars line length)

You can find the bash script here: https://gist.github.com/natterstefan/56e57bdae76e40eb67abeb569ea39b6b.

## How to update

1. [Download the Workflow](https://github.com/natterstefan/alfred-makerlog/raw/natterstefan/fix-success-message-without-successful-result/MakerlogFlow.alfredworkflow)
2. Setup the environment variable ⬇️ 

image
(https://d.pr/i/3CBnSL/jGPMDvv4xZ)

----

Until the PR was merged, you can [download the version of this branch here](https://github.com/natterstefan/alfred-makerlog/raw/natterstefan/fix-success-message-without-successful-result/MakerlogFlow.alfredworkflow).

### CODE REVIEW

**Comment by rasulkireev** [comment]
Ok, so, I'm able to submit todo, successes, etc., via the makerlog-cli. When I'm trying to submit them via alfred (this PR version) I get this message:

Screen Shot 2020-10-02 at 10 21 00 AM

At least, it is not a success. Do you know why this might be happening?

**Comment by natterstefan** [comment]
Hi @rasulkireev, thanks for the feedback. I've added a "How to update" section above. Can you try it, please?

**Comment by rasulkireev** [comment]
Yep, should have noticed the instruction. I added the FILE_PATH variable. I now get the following message.

Screen Shot 2020-10-02 at 12 05 28 PM

How can I debug?

**Comment by rasulkireev** [comment]
@natterstefan ,

Ok, just checked my Makerlog account, and the task was added successfuly. Not sure why he message says "not added", but it was added. Nice.

**Comment by natterstefan** [comment]
@rasulkireev ah, interesting. I gotta check that. Do you have some time tomorrow to do a quick call and debug it together? I'd like to know what happened on your side. If you are willing to debug this with me, of course.

Just send me a DM on Twitter, so we can schedule a meeting.

**Comment by natterstefan** [comment]
@rasulkireev, can you please test the latest version again? I've just pushed a fix https://github.com/meSingh/alfred-makerlog/pull/3/commits/d450fd503bf47e085b2a6cdb3ffa39e65ac7d103.

**Comment by rasulkireev** [comment]
@natterstefan All good! Works nicely.

**Comment by natterstefan** [comment]
Awesome! Now we have to wait for @meSingh's feedback. 🤞

**Comment by meSingh** [comment]
@natterstefan Looks good! Thanks for the PR.

**Comment by natterstefan** [comment]
You're welcome, @meSingh. I am glad I was of help to you and others.

**Comment by jerzygangi** [comment]
> Then download the [latest version here](https://github.com/meSingh/alfred-makerlog/releases/latest) & open it in Alfred to install this workflow.

@meSingh @natterstefan FYI, looks like this PR never made it into the latest release. Anyone following the download link in the `README` (above) will not be able to use `FILE_PATH` enhancement.

**Comment by meSingh** [comment]
@jerzygangi added a new release: 

https://github.com/meSingh/alfred-makerlog/releases/tag/0.2

Thanks for pointing it out.

**Pull request merged**
